### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by cmcnamara87** [uq-eresearch/midja-map#1]
variables
- [ ] proportion of population that is indigenous
- [ ] average number of people per bedroom
- [ ] proportion of dwellings requiring 1 or more extra bedrooms
- [ ] average number of people per dwelling
- [ ] proportion with multi-family households

dependent variables
